[package]
name = "date_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
chrono = "0.4.22"
julianday = "1.2.0"
proptest = "1.0.0"

[build-dependencies]
cc = "1.0.73"
